- lms/static/lms/js/build.js
- webpack.common.config.js
Removed the code specific to the Edly Themes
**JIRA:** 
https://edlyio.atlassian.net/browse/EDE-631
> Removed edly theme specific code

- lms/static/lms/js/build.js
- webpack.common.config.js
> release-2020-07-09

- cms/djangoapps/contentstore/views/public.py
- openedx/core/djangoapps/user_authn/cookies.py
**JIRA:** 
https://edlyio.atlassian.net/browse/EDE-739
- Fixes the user cookies
- Fixes where the sign-in page is still visible to the signed-in user on studio
> Fix User cookie and studio signin page issue

- common/djangoapps/student/admin.py
Change the org field from `TextField` to `ChoiceField` in Course Access Roles.
> Change the org field to Choice field in Course Access Role Model

- cms/static/js/views/utils/create_course_utils.js
- cms/static/js/views/utils/create_library_utils.js
Fix organization list issue in studio course/library creation form
**JIRA:** 
https://edlyio.atlassian.net/browse/EDE-766
> Fix organization list issue in studio course/library creation form

- lms/envs/common.py
- lms/static/js/student_account/models/user_account_model.js
- lms/static/js/student_account/views/account_settings_factory.js
- openedx/core/djangoapps/user_api/accounts/api.py
- openedx/core/djangoapps/user_api/accounts/serializers.py
- openedx/core/djangoapps/user_api/accounts/settings_views.py
Add account additional fields on account setting page
**JIRA:** 
https://edlyio.atlassian.net/browse/EDE-762
**Merge checklist:**
**Post merge:**
**Note:** Please add screenshots for any viewable change.
> additional fields on account settings page

- cms/envs/common.py
- lms/envs/common.py
- openedx/features/edly/models.py
- openedx/features/redhouse_features/__init__.py
- openedx/features/redhouse_features/apps.py
- openedx/features/redhouse_features/management/commands/sync_users_data.py
Add a management command to create appropriate roles and organization for existing users.
**JIRA:** 
https://edlyio.atlassian.net/browse/EDE-749
> Add management command to sync users data wrt to edly requirements

- common/djangoapps/student/views/management.py
- lms/djangoapps/courseware/views/views.py
Added a check for archived courses
**JIRA:** 
https://edlyio.atlassian.net/browse/EDE-840
> Added a check for archived courses

- lms/static/js/student_account/views/FormView.js
- lms/static/js/student_account/views/RegisterView.js
- openedx/core/djangoapps/user_api/accounts/__init__.py
- openedx/core/djangoapps/user_api/accounts/api.py
- openedx/core/djangoapps/user_api/errors.py
- openedx/core/djangoapps/user_api/validation/views.py
Added validation on all additional fields in signin form.
**JIRA:** 
https://edlyio.atlassian.net/browse/EDE-758
**Merge checklist:**
**Post merge:**
> Validation on additional signin fields in signin form

- openedx/core/djangoapps/ace_common/template_context.py
- Added LMS_ROOT_URL in password reset email template
**JIRA:** 
https://edlyio.atlassian.net/browse/EDE-812
> Added LMS_ROOT_URL in password reset email template

- openedx/core/djangoapps/user_api/api.py
Removed the Honor code from the registration page.
> Remove honor code link

- cms/envs/common.py
[EDE-839] Turn on advance xblock's in all of the courses by default
Description:
JIRA:
https://edlyio.atlassian.net/browse/EDE-839****
Fixed PDF xblock integration
> Zubair/ede 839/turn on advance xblock by default

- common/lib/xmodule/xmodule/modulestore/django.py
Fixed Preview Site Not Found
**JIRA:** 
https://edlyio.atlassian.net/browse/EDE-902
> Fixed Preview Site Not Found

- requirements/edx/development.txt
Added Free Text Response in Requirement
> Added Free Text Response in Requirement

- lms/urls.py
- openedx/features/redhouse_features/urls.py
- openedx/features/redhouse_panel/urls.py
Update URLs as per new location of `redhoues-panel` app
> Update URLs for redhouse panel

- openedx/features/redhouse_panel/api/v0/serializers.py
- openedx/features/redhouse_panel/api/v0/tests/test_views.py
- openedx/features/redhouse_panel/api/v0/urls.py
- openedx/features/redhouse_panel/api/v0/views.py
add site API to return name and address (from site configurations)
**JIRA:** 
https://edlyio.atlassian.net/browse/EDE-899
**Merge checklist:**
**Post merge:**
> add site API

- openedx/features/redhouse_panel/api/v0/tests/test_users_account_stats.py
- openedx/features/redhouse_panel/api/v0/urls.py
- openedx/features/redhouse_panel/api/v0/users_account_stats.py
- openedx/features/redhouse_panel/api/v0/views.py
**JIRA:** 
https://edlyio.atlassian.net/browse/EDE-898
**Testing instructions:**
1. Login with a staff user
2. `<LMS SITE DOMAIN>/redhouse-panel/api/v0/sites/<LMS SITE ID>/account_stats/`
3. Result will be something like this `{'instuctor_count': 10, 'student_count': 100}`
> Review Instructor/Student Count API

- cms/static/js/views/settings/main.js
Disabled "emoticons" Plugin in TinyMCE in Course Settings Detail Page
**JIRA:** 
https://edlyio.atlassian.net/browse/EDE-985
> Review Disabled "emoticons" Plugin TinyMCE

- cms/envs/common.py
- common/djangoapps/student/admin.py
- common/djangoapps/student/helpers.py
- lms/envs/common.py
**JIRA:** 
https://edlyio.atlassian.net/browse/EDE-979
> Review Support for Edly Staff Group for Django Admin

- openedx/features/redhouse_panel/api/v0/serializers.py
- openedx/features/redhouse_panel/api/v0/tests/test_user_active_status.py
- openedx/features/redhouse_panel/api/v0/urls.py
- openedx/features/redhouse_panel/api/v0/views.py
**Description:** Added API to change user active status 
**JIRA:** 
https://edlyio.atlassian.net/browse/ede-890*
> Review API for to change user active status 

- openedx/features/redhouse_panel/api/v0/serializers.py
- openedx/features/redhouse_panel/api/v0/views.py
**Description:** EDE-890 updated user serializer fields
**JIRA:** 
https://edlyio.atlassian.net/browse/EDE-890
> EDE-890 updated user serializer fields

- openedx/features/xviewer/static/js/XViewer/Components/viewer.js
Update the code for XViewer tab with the latest code provided. The latest code removes the header in XVIEWER tab.
**JIRA:** 
https://edlyio.atlassian.net/browse/EDLY-1056
> remove header in xviewer

- openedx/features/xviewer/plugins.py
Hide the XVIEWER tab for anonymous and unenrolled users.
**JIRA:** 
N/A
> Hide XVIEWER tab for anonymous and unenrolled users

- openedx/features/redhouse_panel/api/v0/serializers.py
- openedx/features/redhouse_panel/helpers.py
- openedx/features/redhouse_panel/message_types.py
- openedx/features/redhouse_panel/templates/redhouse_panel/edx_ace/passwordset/email/body.html
- openedx/features/redhouse_panel/templates/redhouse_panel/edx_ace/passwordset/email/body.txt
- openedx/features/redhouse_panel/templates/redhouse_panel/edx_ace/passwordset/email/from_name.txt
- openedx/features/redhouse_panel/templates/redhouse_panel/edx_ace/passwordset/email/head.html
- openedx/features/redhouse_panel/templates/redhouse_panel/edx_ace/passwordset/email/subject.txt
- Send password set email to the user (Redhouse Admin Panel) #58
> release-2020-10-28

- openedx/core/djangoapps/content/course_overviews/models.py
uses simple query filter instead of regex filter (#72)
> Release candidate 
